# Basis
dnsmasq_pkg_name: "dnsmasq"
dnsmasq_service_name: "dnsmasq"
dnsmasq_conf_file: "/etc/dnsmasq.conf"
dnsmasq_dhcp_hosts_file: "/etc/dnsmasq.d/dhcp-hosts.conf"
dnsmasq_include_dir: "/etc/dnsmasq.d"
dnsmasq_user: "dnsmasq"

# Interface, Netz
dhcp_interface: "enp0s8"
dhcp_network_cidr: "192.168.111.0/24"
dhcp_gateway: "192.168.111.1"
dhcp_range_start: "192.168.111.100"
dhcp_range_end: "192.168.111.200"
dhcp_netmask: "255.255.255.0"

# Optionen
dhcp_dns_servers: ["192.168.111.1"]
dhcp_domain: "lan"
dhcp_lease_time: "12h"
dhcp_ntp_servers: []

# Statische Leases
dhcp_static_leases: []

# dnsmasq Allgemein
enable_dns_feature: true
listen_address_dns: "192.168.111.1"
