---
- name: Stelle sicher, dass nftables-Service aktiv ist
  listen: reload nftables
  become: true
  ansible.builtin.systemd:
    name: nftables
    state: started
    enabled: true

- name: 
  listen: reload nftables
  become: true
  ansible.builtin.command: "nft -f {{ nft_main_conf }}"
  changed_when: false