# Host-Overrides Beispiel
dhcp_interface: "enp0s8"
dhcp_gateway: "192.168.111.1"
dhcp_range_start: "192.168.111.100"
dhcp_range_end: "192.168.111.200"
dhcp_netmask: "255.255.255.0"
dhcp_dns_servers:
  - "192.168.111.1"
  - "1.1.1.1"
dhcp_domain: "lab.local"
dhcp_lease_time: "12h"
dhcp_ntp_servers: []
dhcp_static_leases:
  - { mac: "00:11:22:33:44:55", ip: "192.168.111.50", name: "fileserver" }
  - { mac: "AA:BB:CC:DD:EE:FF", ip: "192.168.111.51", name: "printer01" }
enable_dns_feature: false
listen_address_dns: "0.0.0.0"